/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '17-7-9 下午9:12' with Gradle 3.2.1
 *
 * @author Administrator, @date 17-7-9 下午9:12
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
